"""
Generated by Claude Code.
"""


import queue
import threading
import tkinter as tk
from datetime import datetime
from tkinter import filedialog, messagebox, ttk

from src.extract import extract
from src.extract.extract import (
    ExtractError,
    ExtractPathError,
    ExtractReadError,
)

DATE_FORMAT = "%Y-%m-%d"


def is_valid_date_string(value: str) -> bool:
    try:
        datetime.strptime(value, DATE_FORMAT)
        return True
    except ValueError:
        return False


def format_summary(stats: dict) -> str:
    return (
        f"전체 처리 행 수: {stats['total']}\n"
        f"성공: {stats['success']}\n"
        f"Skip: {stats['skipped']}"
    )


def main() -> None:
    root = tk.Tk()
    root.title("IRS/CRS 현금흐름 변환기")

    input_path_var = tk.StringVar(value="")
    output_path_var = tk.StringVar(value="")
    eval_date_var = tk.StringVar(value="")
    status_var = tk.StringVar(value="대기 중")

    result_queue: queue.Queue = queue.Queue()

    frame_input = ttk.Frame(root, padding=8)
    frame_input.pack(fill="x")
    btn_select_input = ttk.Button(frame_input, text="입력 파일 선택")
    btn_select_input.grid(row=0, column=0, sticky="w")
    lbl_input_path = ttk.Label(frame_input, textvariable=input_path_var)
    lbl_input_path.grid(row=0, column=1, sticky="w", padx=(8, 0))
    input_path_var.set("(선택되지 않음)")

    frame_output = ttk.Frame(root, padding=8)
    frame_output.pack(fill="x")
    btn_select_output = ttk.Button(frame_output, text="저장 위치 선택")
    btn_select_output.grid(row=0, column=0, sticky="w")
    lbl_output_path = ttk.Label(frame_output, textvariable=output_path_var)
    lbl_output_path.grid(row=0, column=1, sticky="w", padx=(8, 0))
    output_path_var.set("(선택되지 않음)")

    frame_eval_date = ttk.Frame(root, padding=8)
    frame_eval_date.pack(fill="x")
    lbl_eval_date_caption = ttk.Label(frame_eval_date, text="평가일")
    lbl_eval_date_caption.grid(row=0, column=0, sticky="w")
    entry_eval_date = ttk.Entry(frame_eval_date, textvariable=eval_date_var, width=12)
    entry_eval_date.grid(row=0, column=1, sticky="w", padx=(8, 0))
    lbl_eval_date_hint = ttk.Label(frame_eval_date, text="(YYYY-MM-DD)", foreground="gray")
    lbl_eval_date_hint.grid(row=0, column=2, sticky="w", padx=(8, 0))

    btn_run = ttk.Button(root, text="실행", state="disabled")
    btn_run.pack(fill="x", padx=8, pady=(0, 8))

    frame_status = ttk.Frame(root, padding=8)
    frame_status.pack(fill="x")
    lbl_status = ttk.Label(frame_status, textvariable=status_var)
    lbl_status.pack(fill="x")
    progress_bar = ttk.Progressbar(frame_status, mode="indeterminate")
    progress_bar.pack(fill="x", pady=(4, 0))

    # 실제로 선택된 경로가 아니면(placeholder 문구인 채로 남아있으면) 빈 값으로 취급한다.
    def get_selected_input_path() -> str:
        value = input_path_var.get()
        return "" if value == "(선택되지 않음)" else value

    def get_selected_output_path() -> str:
        value = output_path_var.get()
        return "" if value == "(선택되지 않음)" else value

    def update_run_button_state(*_args) -> None:
        ok = (
            bool(get_selected_input_path())
            and bool(get_selected_output_path())
            and is_valid_date_string(eval_date_var.get())
        )
        btn_run.config(state="normal" if ok else "disabled")

    def on_select_input() -> None:
        try:
            path = extract.prompt_for_input_path()
        except ExtractPathError as e:
            if not e.attempted_path:
                return  # 취소 — 조용히 무시, 정상 흐름
            messagebox.showerror("오류", str(e))
            return
        input_path_var.set(path)
        update_run_button_state()

    def on_select_output() -> None:
        path = filedialog.asksaveasfilename(
            title="저장 위치 선택",
            defaultextension=".csv",
            filetypes=[("CSV files", "*.csv")],
        )
        if not path:
            return  # 취소 — 조용히 무시
        output_path_var.set(path)
        update_run_button_state()

    def worker(input_path: str, output_path: str, evaluation_date) -> None:
        # validate/transform/load는 아직 구현되지 않았을 수 있으므로 지연 import한다.
        # 이렇게 하면 백엔드가 없어도 GUI 셸을 그대로 실행/조작해볼 수 있고,
        # 미구현 상태에서 실행을 누르면 조용히 멈춘 것처럼 보이는 대신
        # 아래 except에서 잡혀 에러 팝업으로 명확히 표시된다.
        try:
            result_queue.put(("status", "추출 중..."))
            extract_result = extract.read_csv(input_path)

            from src.validate import validate

            result_queue.put(("status", "검증 중..."))
            valid_df, _skipped = validate.run(extract_result.dataframe)

            from src.transform import transform

            result_queue.put(("status", "변환 중..."))
            transformed_df = transform.run(valid_df, evaluation_date)

            from src.load import load

            result_queue.put(("status", "저장 중..."))
            load.write_csv(transformed_df, output_path)

            # Validate-skip과 Transform-filter를 하나의 skipped 값으로 합산한다.
            # 팝업 표시용 단순화이며, JSON lines 로그에는 두 카테고리를 별도로
            # 남겨야 한다 (아직 미구현 — 후속 슬라이스에서 처리).
            summary = {
                "total": len(extract_result.dataframe),
                "success": len(transformed_df),
                "skipped": len(extract_result.dataframe) - len(transformed_df),
            }
            result_queue.put(("done", summary))
        except ExtractReadError as e:
            # log_fail_fast(category="extract_read", path=e.path, cause=repr(e.cause))  # TODO: 로깅 슬라이스에서 구현
            result_queue.put(("error", str(e)))
        except ExtractPathError as e:
            # log_fail_fast(category="extract_path", attempted_path=e.attempted_path)  # TODO: 로깅 슬라이스에서 구현
            result_queue.put(("error", str(e)))
        except ExtractError as e:
            # log_fail_fast(category="extract_unknown")  # TODO: 로깅 슬라이스에서 구현
            result_queue.put(("error", str(e)))
        except Exception as e:
            result_queue.put(("error", str(e)))

            

    def poll_queue() -> None:
        try:
            while True:
                kind, payload = result_queue.get_nowait()
                if kind == "status":
                    status_var.set(payload)
                elif kind == "done":
                    progress_bar.stop()
                    btn_run.config(state="normal")
                    messagebox.showinfo("성공", format_summary(payload))
                    return
                elif kind == "error":
                    progress_bar.stop()
                    btn_run.config(state="normal")
                    messagebox.showerror("오류", payload)
                    return
        except queue.Empty:
            pass
        root.after(100, poll_queue)

    def on_run() -> None:
        btn_run.config(state="disabled")
        status_var.set("추출 중...")
        progress_bar.start()
        evaluation_date = datetime.strptime(eval_date_var.get(), DATE_FORMAT).date()
        thread = threading.Thread(
            target=worker,
            args=(get_selected_input_path(), get_selected_output_path(), evaluation_date),
            daemon=True,
        )
        thread.start()
        root.after(100, poll_queue)

    btn_select_input.config(command=on_select_input)
    btn_select_output.config(command=on_select_output)
    btn_run.config(command=on_run)
    eval_date_var.trace_add("write", update_run_button_state)

    update_run_button_state()
    root.mainloop()


if __name__ == "__main__":
    main()
