"""
Generated by Claude Code.
"""


import queue
import threading
import tkinter as tk
from datetime import datetime
from tkinter import filedialog, messagebox, ttk

from src import pipeline
from src.extract import extract
from src.extract.extract import (
    ExtractError,
    ExtractPathError,
    ExtractReadError,
)
from src.runlog import new_run_logger
from src.settings import load_last_settings, save_last_settings

DATE_FORMAT = "%Y-%m-%d"


def is_valid_date_string(value: str) -> bool:
    try:
        datetime.strptime(value, DATE_FORMAT)
        return True
    except ValueError:
        return False


def format_summary(stats: dict) -> str:
    return (
        f"전체 처리 행 수: {stats['total']}\n"
        f"성공: {stats['success']}\n"
        f"Skip: {stats['skipped']}\n"
        f"제외(필터): {stats['filtered']}"
    )


def main() -> None:
    root = tk.Tk()
    root.title("IRS/CRS 현금흐름 변환기")

    contract_path_var = tk.StringVar(value="")
    market_path_var = tk.StringVar(value="")
    cashflow_output_path_var = tk.StringVar(value="")
    discount_output_path_var = tk.StringVar(value="")
    eval_date_var = tk.StringVar(value="")
    status_var = tk.StringVar(value="대기 중")

    result_queue: queue.Queue = queue.Queue()

    # 입력 파일 1: 계약정보 (contract info)
    frame_contract = ttk.Frame(root, padding=8)
    frame_contract.pack(fill="x")
    btn_select_contract = ttk.Button(frame_contract, text="계약정보 파일 선택")
    btn_select_contract.grid(row=0, column=0, sticky="w")
    lbl_contract_path = ttk.Label(frame_contract, textvariable=contract_path_var)
    lbl_contract_path.grid(row=0, column=1, sticky="w", padx=(8, 0))
    contract_path_var.set("(선택되지 않음)")

    # 입력 파일 2: 시장금리입력 (market rate curve)
    frame_market = ttk.Frame(root, padding=8)
    frame_market.pack(fill="x")
    btn_select_market = ttk.Button(frame_market, text="시장금리입력 파일 선택")
    btn_select_market.grid(row=0, column=0, sticky="w")
    lbl_market_path = ttk.Label(frame_market, textvariable=market_path_var)
    lbl_market_path.grid(row=0, column=1, sticky="w", padx=(8, 0))
    market_path_var.set("(선택되지 않음)")

    # 출력 파일 1: 현금흐름매핑 (cashflow mapping)
    frame_cashflow_output = ttk.Frame(root, padding=8)
    frame_cashflow_output.pack(fill="x")
    btn_select_cashflow_output = ttk.Button(frame_cashflow_output, text="현금흐름매핑 저장 위치 선택")
    btn_select_cashflow_output.grid(row=0, column=0, sticky="w")
    lbl_cashflow_output_path = ttk.Label(frame_cashflow_output, textvariable=cashflow_output_path_var)
    lbl_cashflow_output_path.grid(row=0, column=1, sticky="w", padx=(8, 0))
    cashflow_output_path_var.set("(선택되지 않음)")

    # 출력 파일 2: 회차별할인율 (per-installment discount rate)
    frame_discount_output = ttk.Frame(root, padding=8)
    frame_discount_output.pack(fill="x")
    btn_select_discount_output = ttk.Button(frame_discount_output, text="회차별할인율 저장 위치 선택")
    btn_select_discount_output.grid(row=0, column=0, sticky="w")
    lbl_discount_output_path = ttk.Label(frame_discount_output, textvariable=discount_output_path_var)
    lbl_discount_output_path.grid(row=0, column=1, sticky="w", padx=(8, 0))
    discount_output_path_var.set("(선택되지 않음)")

    frame_eval_date = ttk.Frame(root, padding=8)
    frame_eval_date.pack(fill="x")
    lbl_eval_date_caption = ttk.Label(frame_eval_date, text="평가일")
    lbl_eval_date_caption.grid(row=0, column=0, sticky="w")
    entry_eval_date = ttk.Entry(frame_eval_date, textvariable=eval_date_var, width=12)
    entry_eval_date.grid(row=0, column=1, sticky="w", padx=(8, 0))
    lbl_eval_date_hint = ttk.Label(frame_eval_date, text="(YYYY-MM-DD)", foreground="gray")
    lbl_eval_date_hint.grid(row=0, column=2, sticky="w", padx=(8, 0))

    btn_run = ttk.Button(root, text="실행", state="disabled")
    btn_run.pack(fill="x", padx=8, pady=(0, 8))

    frame_status = ttk.Frame(root, padding=8)
    frame_status.pack(fill="x")
    lbl_status = ttk.Label(frame_status, textvariable=status_var)
    lbl_status.pack(fill="x")
    progress_bar = ttk.Progressbar(frame_status, mode="indeterminate")
    progress_bar.pack(fill="x", pady=(4, 0))

    # 실제로 선택된 경로가 아니면(placeholder 문구인 채로 남아있으면) 빈 값으로 취급한다.
    def get_selected_contract_path() -> str:
        value = contract_path_var.get()
        return "" if value == "(선택되지 않음)" else value

    def get_selected_market_path() -> str:
        value = market_path_var.get()
        return "" if value == "(선택되지 않음)" else value

    def get_selected_cashflow_output_path() -> str:
        value = cashflow_output_path_var.get()
        return "" if value == "(선택되지 않음)" else value

    def get_selected_discount_output_path() -> str:
        value = discount_output_path_var.get()
        return "" if value == "(선택되지 않음)" else value

    def update_run_button_state(*_args) -> None:
        ok = (
            bool(get_selected_contract_path())
            and bool(get_selected_market_path())
            and bool(get_selected_cashflow_output_path())
            and bool(get_selected_discount_output_path())
            and is_valid_date_string(eval_date_var.get())
        )
        btn_run.config(state="normal" if ok else "disabled")

    def on_select_contract() -> None:
        try:
            path = extract.prompt_for_input_path()
        except ExtractPathError as e:
            if not e.attempted_path:
                return  # 취소 — 조용히 무시, 정상 흐름
            messagebox.showerror("오류", str(e))
            return
        contract_path_var.set(path)
        update_run_button_state()

    def on_select_market() -> None:
        try:
            path = extract.prompt_for_input_path()
        except ExtractPathError as e:
            if not e.attempted_path:
                return  # 취소 — 조용히 무시, 정상 흐름
            messagebox.showerror("오류", str(e))
            return
        market_path_var.set(path)
        update_run_button_state()

    def on_select_cashflow_output() -> None:
        # initialfile이 없으면 폴더만 고르고 저장을 눌렀을 때 파일명이 비어 있어
        # 다이얼로그가 아무 경로도 반환하지 못한다 — 기본 파일명을 미리 채워
        # "폴더 선택 → 저장"만으로 전체 경로가 나오게 한다.
        path = filedialog.asksaveasfilename(
            title="현금흐름매핑 저장 위치 선택",
            defaultextension=".csv",
            initialfile="현금흐름매핑.csv",
            filetypes=[("CSV files", "*.csv")],
        )
        if not path:
            return  # 취소 — 조용히 무시
        cashflow_output_path_var.set(path)
        update_run_button_state()

    def on_select_discount_output() -> None:
        path = filedialog.asksaveasfilename(
            title="회차별할인율 저장 위치 선택",
            defaultextension=".csv",
            initialfile="회차별할인율.csv",
            filetypes=[("CSV files", "*.csv")],
        )
        if not path:
            return  # 취소 — 조용히 무시
        discount_output_path_var.set(path)
        update_run_button_state()

    def worker(
        contract_path: str,
        market_path: str,
        cashflow_output_path: str,
        discount_output_path: str,
        evaluation_date,
    ) -> None:
        # 오케스트레이션과 JSON lines 로깅(validate-skip/transform-filter/fail-fast)은
        # 전부 pipeline.run_pipeline이 담당한다 (architecture.md §4). 이 worker는
        # 스레드 경계만 책임진다: 진행 메시지를 result_queue로 중계하고, 예외를
        # 에러 팝업 메시지로 변환한다.
        #
        # RunLogger는 메인 파이프라인 try보다 앞에서 별도로 생성한다 — 로그 디렉터리
        # 생성 실패(권한 등) 시에도 GUI가 조용히 멈추지 않아야 한다 (logging_design.md §5).
        try:
            run_logger = new_run_logger()
        except OSError as e:
            result_queue.put(("error", f"로그 디렉터리를 생성할 수 없습니다: {e}"))
            return

        try:
            summary = pipeline.run_pipeline(
                contract_path,
                market_path,
                cashflow_output_path,
                discount_output_path,
                evaluation_date,
                run_logger,
                on_status=lambda msg: result_queue.put(("status", msg)),
            )
            result_queue.put(("done", summary))
        except ExtractReadError as e:
            result_queue.put(("error", f"파일 읽기 실패 ({e.path}): {e}"))
        except ExtractPathError as e:
            result_queue.put(("error", str(e)))
        except ExtractError as e:
            result_queue.put(("error", str(e)))
        except Exception as e:
            result_queue.put(("error", str(e)))



    def poll_queue() -> None:
        try:
            while True:
                kind, payload = result_queue.get_nowait()
                if kind == "status":
                    status_var.set(payload)
                elif kind == "done":
                    progress_bar.stop()
                    btn_run.config(state="normal")
                    status_var.set("완료")
                    messagebox.showinfo("성공", format_summary(payload))
                    return
                elif kind == "error":
                    progress_bar.stop()
                    btn_run.config(state="normal")
                    status_var.set("오류")
                    messagebox.showerror("오류", payload)
                    return
        except queue.Empty:
            pass
        root.after(100, poll_queue)

    def on_run() -> None:
        # 파이프라인 성공/실패와 무관하게 입력값이 다음 실행에 남도록
        # 실행 시작 시점에 바로 저장한다 (실패는 save 내부에서 조용히 무시).
        save_last_settings(
            {
                "contract_path": get_selected_contract_path(),
                "market_path": get_selected_market_path(),
                "cashflow_output_path": get_selected_cashflow_output_path(),
                "discount_output_path": get_selected_discount_output_path(),
                "eval_date": eval_date_var.get(),
            }
        )
        btn_run.config(state="disabled")
        status_var.set("추출 중...")
        progress_bar.start()
        evaluation_date = datetime.strptime(eval_date_var.get(), DATE_FORMAT).date()
        thread = threading.Thread(
            target=worker,
            args=(
                get_selected_contract_path(),
                get_selected_market_path(),
                get_selected_cashflow_output_path(),
                get_selected_discount_output_path(),
                evaluation_date,
            ),
            daemon=True,
        )
        thread.start()
        root.after(100, poll_queue)

    btn_select_contract.config(command=on_select_contract)
    btn_select_market.config(command=on_select_market)
    btn_select_cashflow_output.config(command=on_select_cashflow_output)
    btn_select_discount_output.config(command=on_select_discount_output)
    btn_run.config(command=on_run)
    eval_date_var.trace_add("write", update_run_button_state)

    # 마지막 실행 시 저장된 값으로 필드를 미리 채운다. 빈 값이면 placeholder
    # "(선택되지 않음)"를 유지해야 하므로 값이 있는 키만 set한다.
    # settings.json이 없거나 깨진 경우 load가 빈 dict를 반환하므로 그대로 통과.
    saved = load_last_settings()
    for key, var in (
        ("contract_path", contract_path_var),
        ("market_path", market_path_var),
        ("cashflow_output_path", cashflow_output_path_var),
        ("discount_output_path", discount_output_path_var),
        ("eval_date", eval_date_var),
    ):
        if saved.get(key):
            var.set(saved[key])

    update_run_button_state()
    root.mainloop()


if __name__ == "__main__":
    main()
