"""
Generated by Claude Code.
"""

from __future__ import annotations

import json
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Literal

LogCategory = Literal["validate-skip", "transform-filter", "fail-fast"]


def default_log_dir() -> Path:
    """로그 파일을 쓸 기본 디렉터리를 결정한다.

    PyInstaller onefile로 frozen된 경우 sys._MEIPASS(실행 종료 시 삭제되는 임시
    압축 해제 디렉터리)가 아니라 .exe 파일이 위치한 디렉터리를 기준으로 삼는다.
    """
    if getattr(sys, "frozen", False):
        base = Path(sys.executable).parent
    else:
        base = Path(__file__).resolve().parents[2]
    return base / "logs"


@dataclass(frozen=True)
class RunLogger:
    """파이프라인 실행(run) 1회당 인스턴스 1개. 자신이 쓸 로그 파일 경로를 들고 있다."""

    log_path: Path

    def log(self, category: LogCategory, reason: str, details: dict) -> None:
        entry = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "category": category,
            "reason": reason,
            "details": details,
        }
        line = json.dumps(entry, ensure_ascii=False, default=str)
        with self.log_path.open("a", encoding="utf-8") as f:
            f.write(line + "\n")


def new_run_logger(log_dir: Path | str | None = None) -> RunLogger:
    """새 실행을 위한 로그 파일을 만들고 RunLogger를 반환한다.

    log_dir이 쓰기 불가능한 경로 등으로 생성에 실패하면 OSError(및 그 서브클래스인
    PermissionError 등)를 그대로 전파한다 — 호출부(worker())가 이를 감지해서
    GUI에 에러를 표시할 책임을 진다 (logging_design.md §5 참조).
    """
    resolved_dir = Path(log_dir) if log_dir is not None else default_log_dir()
    resolved_dir.mkdir(parents=True, exist_ok=True)
    run_id = datetime.now().strftime("%Y%m%d_%H%M%S")
    return RunLogger(log_path=resolved_dir / f"run_{run_id}.jsonl")
